Srt html styling
asticode/go-astisub pull request #121
Opened 2024-11-15 17:48 UTC by justin-taylor

This PR resurrects https://github.com/asticode/go-astisub/pull/96 The changes from the PR have been re-applied and made to work with the mast recent changes. For our use-case we often run into an srt file being uploaded with stylings that are then broken when converted to webvtt.

2024-11-16 11:00 UTC, asticode requested changes
Thanks for picking up this PR ❤️ 

A few changes are needed for tests 👍

2024-11-16 11:00 UTC, asticode commented on subtitles_test.go
> +func assertSRTSubtitleStyles(t *testing.T, i *astisub.Subtitles) {
This function should be removed based on my previous comment

2024-11-18 16:30 UTC, justin-taylor commented
> Thanks for picking up this PR ❤️
> 
> A few changes are needed for tests 👍

All comments have been addressed.

2024-11-20 11:34 UTC, merged

2024-11-20 11:35 UTC, asticode commented
Thanks for the PR! ❤️ 

Let me know whether you need a tag 👍

2024-11-20 17:48 UTC, justin-taylor commented
> Thanks for the PR! ❤️
> 
> Let me know whether you need a tag 👍

A tag would be great! Thank you.

2024-11-21 08:22 UTC, asticode commented
I've created a `v0.30.0` tag 👍