TTML to VTT style migration
asticode/go-astisub pull request #48
Opened 2021-07-09 15:06 UTC by Avishek-Gulshan

- Update TTM L parser to push parent style to child tags
- Creating new custom style classes by combining inline style and style class
- Added additional style propagation from TTML to VTT

2021-07-09 15:17 UTC, Avishek-Gulshan commented
Hi,

Can you please have a look at this PR. See if this makes sense

2021-07-13 11:17 UTC, Avishek-Gulshan commented
Hi, Please take a look at this PR

2021-07-14 07:32 UTC, asticode commented
This is a big PR and I'm pretty busy right now, I'll need some time to review it

2021-08-11 08:11 UTC, asticode requested changes
This is a huge PR, I've not reviewed everything but let start from here.

You need to fix tests as well.

2021-08-11 08:11 UTC, asticode commented on ttml.go
> +func checkIfCustomStyleExists(styleMap map[Style]string, style *Style) (bool, string) {
Could you transform this to `func (ss ttmlCustomStyles) exists(s *Style) (id string, ok bool)` instead ?

2021-08-11 08:11 UTC, asticode commented on ttml.go
> +					ok, id := checkIfCustomStyleExists(customStyleMap, newStyle)
Could you make this a one liner : `if ok, id := checkIfCustomStyleExists(customStyleMap, newStyle); ok {`

2021-08-11 08:11 UTC, asticode commented on ttml.go
> +	var customStyleMap = make(map[Style]string)
I feel it should be the other way around and with a pointer `var customStyleMap = make(map[string]*Style)`, and you should rename this variables to `customStyles`

2023-11-09 09:06 UTC, NhanNguyen700 commented
This one looks interesting, any further work?

2023-11-09 13:16 UTC, asticode commented
Requested changes need to be addressed (this was the first part of my review) but based on the fact that this PR is pretty old, I doubt the OP will ever do it.

If you feel like it, you can pick it up 👍

2024-02-14 13:03 UTC, closed without merging