Add Japanese&Chinese
asticode/go-astisub pull request #53
Opened 2021-08-05 02:23 UTC by EldersJavas

reference
REC-xml-20081126
RFC1766
EBU tech 3264

2021-08-05 10:56 UTC, asticode requested changes
This is a nice PR.

Just minor changes needed though

2021-08-05 10:56 UTC, asticode commented on language.go
> +	LanguageChinese = "chinese"
Could you order constants alphabetically?

2021-08-05 10:56 UTC, asticode commented on stl.go
> +	stlCountryCodeChinese = "CHN"
Could you order constants alphabetically?

2021-08-05 10:56 UTC, asticode commented on stl.go
> +	stlLanguageCodeChinese   = "75"
Could you order constants alphabetically?

2021-08-05 10:56 UTC, asticode commented on stl.go
> +	Set(stlLanguageCodeNorwegian, LanguageNorwegian).
Could you order lines alphabetically?

2021-08-05 10:56 UTC, asticode commented on ttml.go
> +	ttmlLanguageChinese   = "zh"
Could you order constants alphabetically?

2021-08-05 10:56 UTC, asticode commented on ttml.go
> +	Set(ttmlLanguageNorwegian, LanguageNorwegian).
Could you order lines alphabetically?

2021-08-10 12:04 UTC, EldersJavas commented
sloved :)

2021-08-10 14:58 UTC, merged

2021-08-10 14:59 UTC, asticode commented
FYI I've created a `v0.16.0` tag