webvtt: Handle X-TIMESTAMP-MAP header
asticode/go-astisub pull request #63
Opened 2022-01-13 06:41 UTC by anupcshan

When specified, X-TIMESTAMP-MAP should be used to compute an offset for
each subtitle record in the file.

2022-01-14 08:25 UTC, asticode requested changes
This is a great PR ! ❤️ 

Some changes needed though.

Also, could add a test inspired by [this one](https://github.com/asticode/go-astisub/blob/master/webvtt_test.go#L49) to test a simple full webvtt file with only a couple of items and a timestamp map, to test it's taken into account?

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +func computeOffsetFromTimestampMap(line string) (time.Duration, error) {
Could you rename this function to `parseTimestampMapWebVTT`

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +	right := strings.Split(line, "=")[1]
You should check whether `len(strings.Split(line, "=")) > 0` otherwise it may panic here

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +		splits := strings.SplitN(split, ":", 2)
You should check `len(splits) > 1` otherwise it may panic below

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +		switch splits[0] {
could you switch on `string.ToLowerCase(splits[0])` instead ? and replace `case` values with their lower case version ? that way the lib will handle `LOCAL` as well as `local` for instance

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +func computeOffsetFromTimestampMap(line string) (time.Duration, error) {
Could you use named return arguments : `(timeOffset time.Duration, err error)`?

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +	var timeOffset time.Duration
You can remove this line if we use named return arguments

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +			var err error
You can remove this line if we use named return arguments

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +			var err error
You can remove this line if we use named return arguments

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +				return timeOffset, err
Could you wrap the error : 

```go
if local, err = parseDurationWebVTT(splits[1]); err != nil {
  err = fmt.Errorf("astisub: parsing webvtt duration failed: %w", err)
  return
}
```

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +			mpegts, err = strconv.ParseInt(splits[1], 10, 0)
Could you wrap the error : 

```go
if mpegts, err = strconv.ParseInt(splits[1], 10, 0); err != nil {
  err = fmt.Errorf("astisub: parsing int %s failed: %w", splits[1], err)
  return
}
```

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +				err = fmt.Errorf("Found timestamp map after processing subtitle items")
Can you use `errors.New` instead, prefix error with `astisub: ` and start with a lower case letter ? `astisub: found timestamp map after processing subtitle items`

2022-01-14 08:25 UTC, asticode commented on webvtt.go
> +			timeOffset, err = computeOffsetFromTimestampMap(line)
Could you wrap the error : 

```go
if timeOffset, err = parseTimestampMapWebVTT(line); err != nil {
  err = fmt.Errorf("astisub: parsing webvtt timestamp map failed: %w", err)
  return
}
```

2022-01-14 08:25 UTC, asticode commented on webvtt_internal_test.go
> +		{
Could you add cases where :

- `local` is not empty and `mpegts` is empty
- both `local` and `mpegts` are not empty

2022-01-14 19:50 UTC, anupcshan commented
> This is a great PR ! heart
> 
> Some changes needed though.
> 
> Also, could add a test inspired by [this one](https://github.com/asticode/go-astisub/blob/master/webvtt_test.go#L49) to test a simple full webvtt file with only a couple of items and a timestamp map, to test it's taken into account?

Thanks for the detailed review! I've made all the suggested changes and added a test with a full webvtt.

2022-01-15 09:23 UTC, asticode approved these changes
❤️

2022-01-15 09:23 UTC, merged

2022-01-15 09:24 UTC, asticode commented
FYI I've added a `v0.20.0` tag